### ISSUE TITLE
Need an overview of how to upload Pacs

### ISSUE THREAD

**Issue by jogapps** [bioinformatics-ua/dicoogle#618] opened 2022-10-22 09:53 UTC
Going through the platform and I can't seem to find a way of uploading pacs. How do I go about it and what routes do I need for uploading it?

**Comment by bastiao** [comment] 2022-10-22 10:01
Dicoogle allows to upload the studies by DICOM STORE SCP service. You can use any DICOM STORE SCU tool (i.e. [dicom-rs](https://github.com/Enet4/dicom-rs) has tool for `storescu`  or any other)

Make sure that you have Services - Storage started (see more info here https://bioinformatics-ua.github.io/dicoogle-learning-pack/docs/configuring/)

Closing this issue, because it is not a bug/feature request.

**Closed by bastiao** 2022-10-22 10:01 UTC
