### ISSUE TITLE
Improve Rest Service Routing mechanism

### ISSUE THREAD

**Issue by luissribeiro** [bioinformatics-ua/dicoogle#111] opened 2015-09-10 14:59 UTC
Since dicoogle platform follows the strategy for Rest Plugins:

router.attach(TestResource.toString(), TestResource.class);

which enables hiearquical routes, by returning in the toString() method something like:

return "test/{someStuff}";

I suggest make an abstract class that forces the definition of a setRoute method for more complex routes.

**Comment by Enet4** [comment] 2015-09-11 10:00
Could you provide an example on using that abstraction? In addition, wouldn't the provision of Restlet entities instead of Restlet server resources also solve that issue?

**Comment by bastiao** [comment] 2015-09-11 10:01
Just for the record: https://github.com/bioinformatics-ua/dicoogle/tree/wip/restlet_plugin_interface

**Comment by Enet4** [comment] 2015-09-11 10:05
Indeed, I devised that solution and put it in that branch, because I figured it would make web service development under Restlet more flexible and intuitive.

**Comment by bastiao** [comment] 2015-12-13 00:30
because it is duplicated, we are going to close this one.
nevertheless, the issue is still a nice feature to have.

**Closed by bastiao** 2015-12-13 00:30 UTC
Labels: duplicate, enhancement
