### ISSUE TITLE
[webapp] Syntax to search by numeric is not working properly

### ISSUE THREAD

**Issue by bastiao** [bioinformatics-ua/dicoogle#144] opened 2015-10-13 22:15 UTC
Queries such as the one down does not works properly
```
SliceLocation:Numeric:[10.0 TO 20.0] 
```

Reported by BMD Software.

**Comment by Enet4** [comment] 2015-10-14 09:29
My tests show that those queries work with the _keyword_ flag turned on. The transformations that we perform on a free text query are actually breaking it.

> ERROR lucene.LuceneQuery (LuceneQuery.java:133) - Error parsing query
org.apache.lucene.queryParser.ParseException: Cannot parse '(OperatorName:SliceLocation:[10.0 OR NumberOfStudyRelatedInstances:SliceLocation:[10.0 OR Manufacturer:SliceLocation:[10.0 OR StudyDescription:SliceLocation:[10.0 OR StudyTime:SliceLocation:[10.0 OR ModalitiesInStudy:SliceLocation:[10.0 OR StudyInstanceUID:SliceLocation:[10.0 OR SeriesInstanceUID:SliceLocation:[10.0 OR PregnancyStatus:SliceLocation:[10.0 OR StudyID:SliceLocation:[10.0 OR PatientSex:SliceLocation:[10.0 OR SeriesNumber:SliceLocation:[10.0 OR SeriesDescription:SliceLocation:[10.0 OR InstitutionName:SliceLocation:[10.0 OR InstitutionDepartmentName:SliceLocation:[10.0 OR Priority:SliceLocation:[10.0 OR PatientBirthDate:SliceLocation:[10.0 OR PerformedLocation:SliceLocation:[10.0 OR PatientTelephoneNumbers:SliceLocation:[10.0 OR PerformingPhysicianName:SliceLocation:[10.0 OR AccessionNumber:SliceLocation:[10.0 OR ManufacturerModelName:SliceLocation:[10.0 OR ReferringPhysicianName:SliceLocation:[10.0 OR PatientID:SliceLocation:[10.0 OR StudyDate:SliceLocation:[10.0 OR Modality:SliceLocation:[10.0 OR PatientAge:SliceLocation:[10.0 OR PatientName:SliceLocation:[10.0 OR SOPInstanceUID:SliceLocation:[10.0OR others:SliceLocation:[10.0 ) AND (OperatorName:TO OR NumberOfStudyRelatedInstances:TO OR Manufacturer:TO OR StudyDescription:TO OR StudyTime:TO OR ModalitiesInStudy:TO OR StudyInstanceUID:TO OR SeriesInstanceUID:TO OR PregnancyStatus:TO OR StudyID:TO OR PatientSex:TO OR SeriesNumber:TO OR SeriesDescription:TO OR InstitutionName:TO OR InstitutionDepartmentName:TO OR Priority:TO OR PatientBirthDate:TO OR PerformedLocation:TO OR PatientTelephoneNumbers:TO OR PerformingPhysicianName:TO OR AccessionNumber:TO OR ManufacturerModelName:TO OR ReferringPhysicianName:TO OR PatientID:TO OR StudyDate:TO OR Modality:TO OR PatientAge:TO OR PatientName:TO OR SOPInstanceUID:TOOR others:TO ) AND (OperatorName:20.0] OR NumberOfStudyRelatedInstances:20.0] OR Manufacturer:20.0] OR StudyDescription:20.0] OR StudyTime:20.0] OR ModalitiesInStudy:20.0] OR StudyInstanceUID:20.0] OR SeriesInstanceUID:20.0] OR PregnancyStatus:20.0] OR StudyID:20.0] OR PatientSex:20.0] OR SeriesNumber:20.0] OR SeriesDescription:20.0] OR InstitutionName:20.0] OR InstitutionDepartmentName:20.0] OR Priority:20.0] OR PatientBirthDate:20.0] OR PerformedLocation:20.0] OR PatientTelephoneNumbers:20.0] OR PerformingPhysicianName:20.0] OR AccessionNumber:20.0] OR ManufacturerModelName:20.0] OR ReferringPhysicianName:20.0] OR PatientID:20.0] OR StudyDate:20.0] OR Modality:20.0] OR PatientAge:20.0] OR PatientName:20.0] OR SOPInstanceUID:20.0]OR others:20.0] )': Encountered " ":" ": "" at line 1, column 27.
Was expecting one of:
    <AND> ...
    <OR> ...
    <NOT> ...
    "+" ...
    "-" ...
    "(" ...
    ")" ...
    "*" ...
    "^" ...
    <QUOTED> ...
    <TERM> ...
    <FUZZY_SLOP> ...
    <PREFIXTERM> ...
    <WILDTERM> ...
    "[" ...
    "{" ...
>    <NUMBER> ...
>    
>	at org.apache.lucene.queryParser.QueryParser.parse(QueryParser.java:211) ~[lucene-2.0.1-SNAPSHOT.jar:?]
	at dicoogle.lucene.LuceneQuery.query(LuceneQuery.java:131) [lucene-2.0.1-SNAPSHOT.jar:?]
	at pt.ua.dicoogle.plugins.PluginController$1.call(PluginController.java:508) [dicoogle.jar:1.0-SNAPSHOT]
	at pt.ua.dicoogle.plugins.PluginController$1.call(PluginController.java:505) [dicoogle.jar:1.0-SNAPSHOT]
        ...

**Comment by bastiao** [comment] 2015-10-14 09:31
Yes, I know it. It is a problem in client side. I know exactly how to solve it.

**Comment by Enet4** [comment] 2015-11-04 16:40
This concerns advanced queries that should be interpreted as keyword-based. Marking this as a duplicate of #154.

**Closed** 2015-11-04 17:54 UTC
Labels: bug, duplicate, webapp
