### ISSUE TITLE
API authentication request

### ISSUE THREAD

**Issue by gdevenyi** [bioinformatics-ua/dicoogle#696] opened 2024-08-12 14:33 UTC
The WebUI has a username/password facility, meanwhile the API has no authentication whatsoever.

I can simply run a curl POST against the user endpoint and create an admin-level user and login.

**Comment by Enet4** [comment] 2024-10-14 16:37
Closing as a duplicate of #98, which proposes stricter authorization mechanisms in the API. Until then, Dicoogle instances are not prepared to be exposed to the wider Web.

**Closed by Enet4** 2024-10-14 16:37 UTC
Labels: duplicate, dicoogle-core
